export const ADD_ERRORS = 'ADD_ERRORS'
export const ADD_ERRORS_REQUESTED = 'ADD_ERRORS_REQUESTED'
export const REMOVE_ERROR = 'REMOVE_ERROR'
export const REMOVE_ERROR_REQUESTED = 'REMOVE_ERROR_REQUESTED'
